# Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array 
té més d’una dimensió, ha de mostrar un missatge d’error.



In [1]:
# Primer de tot cridem la llibreria "numpy" que farem servir per desenvolupar les opercions següents.

import numpy as np

In [2]:
def stat_summ(array):                                         # definim la funció amb un array com a argument
                                                              # tot el següent fins el "if" será la descripció estadística
    print("Resum Estadístic Bàsic")                             
    print("Mitjana               :", np.median(array))
    print("Mitja                 :", np.mean(array))
    print("Desviació estàndard   :", np.std(array))
    print("Variança              :", np.var(array))
    
    if array.ndim != 1:                                       # Ara fem servir .ndim per corrobar si l'array que hi posarem tindrà més d'una dimensió
        print("Error! Aquest array té més d'una dimensió")

numeros_primos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]         # Ara creem l'array a partir d'una llista prèvia
array_primos = np.array(numeros_primos)
stat_summ(array_primos)                                       # Ara cridem la funció i com que l'array ès d'una dimensió doncs no ens avisa d'error.

Resum Estadístic Bàsic
Mitjana               : 12.0
Mitja                 : 12.9
Desviació estàndard   : 8.560957890329796
Variança              : 73.28999999999999


# Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [3]:
def  crea_quadrat(t):                                  # definim la funció amb l'argument "t" on posarem el tamany de la matriu
    return np.random.randint(0, 100, size=(t,t))       # la funció tornarà un valor aleatori entero entre 0 i 100 amb una quantit de elements igual en files com a les columnes
                                                       
matriu = crea_quadrat(5)                               # Ara creem la variable que crida a la funció amb l'argument específic del nombre de elements per files i columnes
print(matriu)                                          # imprimim la variable amb la execució de la funció


[[32 30 60  6 56]
 [23 55 70 79 88]
 [ 7 71 28 78 37]
 [60 42 58 62 62]
 [24 84 52 12 89]]


### Exercici 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [65]:
def calcul(taula):                             # Creem la funció amb l'argument "taula"
    col = np.sum(a, axis=0)                    # Ara creem la variable que farà la operació per obtenir la suma total pero columnes amb l'eix 0
    fil = np.sum(a, axis=1)                    # idem a les columnes pero ara amb les files
    
    print("Els totals per columnes son ", col) # Fem la redacció per imprimir posteriorment, cridant el càlcul fet dins de la variable
    print("Els totals per files son ", fil)    # Idem 
    
a = np.arange(12).reshape(4,3)                 # Creem la taula. De dues dimensions a partir d'un rang de 12 elements
resultat = calcul(a)                           # Ara cridem la funció afegint la taula
resultat                                       # Imprimim el resultat

Els totals per columnes son  [18 22 26]
Els totals per files son  [ 3 12 21 30]


### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [80]:
def coef_r(x, y):                                             # fem una funció amb dos paràmetres que seràn els dos arrays d'on es calcularà el coeficient de correlació
                                                              # En el coef de correlació hem de calcular principalment desviacions, tant del array "a" com del array "b"
    a_mean         = np.mean(a)                               # per axiò calculem la mitja
    b_mean         = np.mean(b)                               # idem
    desviacio_a    = a - a_mean                               # calculem desviació
    desviacio_b    = b - b_mean                               # idem
    covariança     = np.sum(desviacio_a * desviacio_b)        # Tot el que hem calculat finalment es tradueix en el càlcul de la covarinça (numerador)
    
    # Ara ve la segonda part. El denominador
    
    desviacio_a_sq = desviacio_a**2                                           # necessitem els quadrats de les desviacions
    desviacio_b_sq = desviacio_b**2                                           # idem
    denominador    = np.sqrt(np.sum(desviacio_a_sq) * np.sum(desviacio_b_sq)) # Per finalment calcular el final de segona part (el denominador)
    
    print("El coeficient de correlació calculat manualment és = ", covariança / denominador) # Per últim imprimim el resultat de l'ecuació divideix la covariança per el denomnador.

a = alçada_cm = np.array([50, 65, 70, 85, 100, 125, 145, 160, 175, 180])      # Creem el primer array
b = edat_anys = np.array([5, 8, 9, 11, 13, 14, 15, 17, 20, 23])               # ara el segon
r = coef_r(a,b)                                                               # Ara cridem la funció amb els parámetres/arrays creats.

print(" El coeficient de correlació calculat automáticament és = ", np.corrcoef(a,b)) # Fem servir l'ecuació automàtica per corroborar.



""" El coeficient de Correlació de de Person (o la r de Person) és de molta utilitat quan necessitem evaluar la relació 
entre dues variables amb categories ordinales. La correlación pot variar entre -1 y + 1. El valor "0" indica que no hi 
ha cap relació lineal entre les variables. Si el valor s'apropa a 1 doncs estem parlant d'una alta relació positiva, es a dir,
que cada vegada que les dades d'una variable augmentan en un sentit, l'altre fa el mateix. Es el cas del meu exemple entre 
la alçada d'una persona i la seva edat. El meu exemple té r de Person de 0.972 per tant porta una forta relació positiva entre
les variables. Mentre que una persona es fa més gran (més edat), augmenta la seva alçada i viceversa."""


El coeficient de correlació calculat manualment és =  0.9723464829857159
 El coeficient de correlació calculat automáticament és =  [[1.         0.97234648]
 [0.97234648 1.        ]]
